### PR TITLE
Fixed pathing issues in iOS post processor

### PR DESCRIPTION
**Pull request by adamschlesinger**
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/372)

### CODE REVIEW

**Review by jkasten2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/372)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @adamschlesinger)

___
*[com.onesignal.unity.ios/Editor/PostProcessBuildPlayer_iOS.cs, line 105 at r1](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/372#-MfiJ1cmACJUYWzhCDiN:-MfiJ1cmACJUYWzhCDiO:b-78z7cm) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/59e9c92a529a82bc829966f83114cb22ca855a53/com.onesignal.unity.ios/Editor/PostProcessBuildPlayer_iOS.cs#L105)):*
> ```Smalltalk
>     public static void OnPostProcessBuild(BuildTarget target, string path)
>     {
>         if (target != BuildTarget.iOS)
> ```

Shouldn't the pre-processor we have already cover this?
```
#if UNITY_IPHONE && UNITY_EDITOR
```
___
*[com.onesignal.unity.ios/Editor/PostProcessBuildPlayer_iOS.cs, line 267 at r1](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/372#-MfiJfnKCBDHBsQX8A8H:-MfiJfnKCBDHBsQX8A8I:b-qlee7w) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/4151910a75513c2a4b091353983e0d838c64d7f6/com.onesignal.unity.ios/Editor/PostProcessBuildPlayer_iOS.cs#L267)):*
> ```Smalltalk
> 
>         project.AddBuildProperty(extensionGUID, "LIBRARY_SEARCH_PATHS",
>             "$(PROJECT_DIR)/Libraries/OneSignal/Platforms/iOS");
> ```

This path needs to be updated yet.

**Review by adamschlesinger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/372)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @jkasten2)

___
*[com.onesignal.unity.ios/Editor/PostProcessBuildPlayer_iOS.cs, line 105 at r1](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/372#-MfiJ1cmACJUYWzhCDiN:-MfiLfy9BGVhDNJRhZeY:b-4oajx6) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/59e9c92a529a82bc829966f83114cb22ca855a53/com.onesignal.unity.ios/Editor/PostProcessBuildPlayer_iOS.cs#L105)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Shouldn't the pre-processor we have already cover this?
```
#if UNITY_IPHONE && UNITY_EDITOR
```
</blockquote></details>

In Editor it does but this will not be adequate for all build solutions. This is fairly standard practice to do both.
___
*[com.onesignal.unity.ios/Editor/PostProcessBuildPlayer_iOS.cs, line 267 at r1](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/372#-MfiJfnKCBDHBsQX8A8H:-MfikLuW1hNaIOFetigc:bppo4kw) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/4151910a75513c2a4b091353983e0d838c64d7f6/com.onesignal.unity.ios/Editor/PostProcessBuildPlayer_iOS.cs#L267)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

This path needs to be updated yet.
</blockquote></details>

Fixed in c7616e8

**Comment by jkasten2** [comment]
___
*[com.onesignal.unity.ios/Editor/PostProcessBuildPlayer_iOS.cs, line 105 at r1](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/372#-MfiJ1cmACJUYWzhCDiN:-MfiqgWN6BH9HhWYi8de:bil021t) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/59e9c92a529a82bc829966f83114cb22ca855a53/com.onesignal.unity.ios/Editor/PostProcessBuildPlayer_iOS.cs#L105)):*
<details><summary><i>Previously, adamschlesinger (Adam Schlesinger) wrote…</i></summary><blockquote>

In Editor it does but this will not be adequate for all build solutions. This is fairly standard practice to do both.
</blockquote></details>

Weird, seems like Unity is not reliably recompiling before running or there is something we don't understand about Unity here. The extra check is good for this PR even if we are not sure to be safe. Would be good to understand it more later. Also for the future, I believe we use the pre-processor solution only in other files that might need to b updated as well.

**Review by jkasten2 — APPROVED** [review]
:lgtm: 
Tested with Unity 2020.3.14f1, Xcode 12.5.1, on an iOS 14.4.1

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/372#-:-MfirhyG3XxtpjD2zY9U:b-nqrcif)* status: all files reviewed, 1 unresolved discussion (waiting on @adamschlesinger)

**Pull request merged**
