### PR TITLE
[CHANGE] Overwrite project's AndroidManifest if diff

### PR DESCRIPTION
**Pull request by adamschlesinger**
### Changed
- Explicitly check for a diff and handle overwrites for the `AndroidManifest.xml` between the project's and package's `OneSignalConfig.plugin`

---
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/488)

### CODE REVIEW

**Review by jkasten2 — CHANGES_REQUESTED** [review]
The code changes themselves look good. The PR doesn't state why though so I'll make some guess, and should add this detail to the PR description if true:

Motivations around the .png check - There is a bug with custom Android Notification Icons getting reverted after the app developer changes them.

Motivations around `OneSignalConfig.plugin/AndroidManifest.xml`:
* "fail fast" by reverting modifications an app developer would make to this file.
* Any changes OneSignal would make to this file in the future would be copied over.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/488#-:-N07B5jO-5AzKIHy4dnC:b-ungdoh)* status: all files reviewed, 1 unresolved discussion (waiting on @adamschlesinger)

___
*[com.onesignal.unity.android/Editor/SetupSteps/ExportAndroidResourcesStep.cs, line 87 at r1](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/488#-N07Byxw89cfdOkTp10O:-N07Byxw89cfdOkTp10P:bdq0nk0) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/a1faab10c0bb95f40fa58f3116556ccf840750d7/com.onesignal.unity.android/Editor/SetupSteps/ExportAndroidResourcesStep.cs#L87)):*
> ```Smalltalk
> 
>                 // don't copy over existing png files
>                 if (fileExportPath.Contains(".png") && !File.Exists(fileExportPath))
> ```

Does this prevent reverting Android icons?

**Review by adamschlesinger — COMMENTED** [review]
The PNG check is just there to ensure they aren't copied over if they already exist. That's not really the goal of this PR but it was a necessary check for part of the goal of the PR which is to overwrite non-png files in the plugin.

> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/488#-:-N07QDEnE66_XoPlyh-y:b-3wnokp)* status: all files reviewed, 1 unresolved discussion (waiting on @adamschlesinger)

**Review by jkasten2 — CHANGES_REQUESTED** [review]
O there is no existing bug with PNGs. I believe however the new code in this PR has a bug though, I commented on the the line of code with more details.

Could we also update the PR description with the reason / motivation / "what is should fix"?

> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/488#-:-N07XVuB6ocXGbbKqar9:bqtaegh)* status: all files reviewed, 1 unresolved discussion (waiting on @adamschlesinger)

___
*[com.onesignal.unity.android/Editor/SetupSteps/ExportAndroidResourcesStep.cs, line 87 at r1](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/488#-N07Byxw89cfdOkTp10O:-N07VglVC5tzehrj164O:b-b8m960) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/a1faab10c0bb95f40fa58f3116556ccf840750d7/com.onesignal.unity.android/Editor/SetupSteps/ExportAndroidResourcesStep.cs#L87)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Does this prevent reverting Android icons?
</blockquote></details>

I think is going to create a bug where it will replace the app developers custom notification icons with the defaults every time this code runs.

I think the indented code you want is:
```C#
// don't copy over existing png files
if (fileExportPath.Contains(".png")) {
   if (!File.Exists(fileExportPath))
      File.Copy(file, fileExportPath);
}
else // all other files should be refreshed
   File.Copy(file, fileExportPath, true);
```

**Review by adamschlesinger — COMMENTED** [review]
This isn't really a "fix" so much as an improvement.

> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/488#-:-N07frRO2f7vIl2ixjMB:b-bh3xyz)* status: all files reviewed, 1 unresolved discussion (waiting on @jkasten2)

___
*[com.onesignal.unity.android/Editor/SetupSteps/ExportAndroidResourcesStep.cs, line 87 at r1](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/488#-N07Byxw89cfdOkTp10O:-N07fwbY1jD-3WNO5jDm:b-erca6z) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/a1faab10c0bb95f40fa58f3116556ccf840750d7/com.onesignal.unity.android/Editor/SetupSteps/ExportAndroidResourcesStep.cs#L87)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

I think is going to create a bug where it will replace the app developers custom notification icons with the defaults every time this code runs.

I think the indented code you want is:
```C#
// don't copy over existing png files
if (fileExportPath.Contains(".png")) {
   if (!File.Exists(fileExportPath))
      File.Copy(file, fileExportPath);
}
else // all other files should be refreshed
   File.Copy(file, fileExportPath, true);
```

</blockquote></details>

`File.Copy` doesn't overwrite existing files by default. It needs to be explicitly told to do so via the bool 3rd parameter. The `Exists` check is explained in the comment block above that it just prevents polluting the Unity console with warnings.

**Review by jkasten2 — CHANGES_REQUESTED** [review]
The fix here interduces a new bug, confirmed it and added more details on the line of code.

Also latest change includes an unintended version bump.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/488#-:-N0Ixsk6D4i4GWum5FUu:bx2q90k)* status: all files reviewed, 2 unresolved discussions (waiting on @adamschlesinger)

___
*[com.onesignal.unity.android/Editor/OneSignalAndroidDependencies.xml, line 6 at r2](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/488#-N0IxmSF6RnwbMcU5JzH:-N0IxmSF6RnwbMcU5JzI:be409kh) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/9cb85aa98774b644eb545f8e82f3aea2b7de99c5/com.onesignal.unity.android/Editor/OneSignalAndroidDependencies.xml#L6)):*
> ```XML
>       <repository>https://repo.maven.apache.org/maven2</repository>
>     </repositories>
>     <androidPackage spec="com.onesignal:OneSignal:4.7.1" />
> ```

Changing the Android native version is out of scope for this PR.
___
*[com.onesignal.unity.android/Editor/SetupSteps/ExportAndroidResourcesStep.cs, line 87 at r1](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/488#-N07Byxw89cfdOkTp10O:-N0IwFbAEBmkhFGzcHcO:bzlgc4) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/a1faab10c0bb95f40fa58f3116556ccf840750d7/com.onesignal.unity.android/Editor/SetupSteps/ExportAndroidResourcesStep.cs#L87)):*
<details><summary><i>Previously, adamschlesinger (Adam Schlesinger) wrote…</i></summary><blockquote>

`File.Copy` doesn't overwrite existing files by default. It needs to be explicitly told to do so via the bool 3rd parameter. The `Exists` check is explained in the comment block above that it just prevents polluting the Unity console with warnings.
</blockquote></details>

I just tested and can confirm it does overwrite existing `.png` icon files!, where my suggested code above does not.

This nesting of the `if` statement is significant vs the `&&`. With the `&&` it falls into `File.Copy(file, fileExportPath, true);` and does overwrite.

**Review by adamschlesinger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/488)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @jkasten2)

___
*[`com.onesignal.unity.android/Editor/SetupSteps/ExportAndroidResourcesStep.cs` line 87 at r1](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/488#-N07Byxw89cfdOkTp10O:-N0allTR3LLPLC_-cHKw:b-896fix) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/a1faab10c0bb95f40fa58f3116556ccf840750d7/com.onesignal.unity.android/Editor/SetupSteps/ExportAndroidResourcesStep.cs#L87)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

I just tested and can confirm it does overwrite existing `.png` icon files!, where my suggested code above does not.

This nesting of the `if` statement is significant vs the `&&`. With the `&&` it falls into `File.Copy(file, fileExportPath, true);` and does overwrite.
</blockquote></details>

Done.
___
*[`com.onesignal.unity.android/Editor/OneSignalAndroidDependencies.xml` line 6 at r2](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/488#-N0IxmSF6RnwbMcU5JzH:-N0akU2t5D_WMhrjE3tp:bxwh2bf) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/9cb85aa98774b644eb545f8e82f3aea2b7de99c5/com.onesignal.unity.android/Editor/OneSignalAndroidDependencies.xml#L6)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Changing the Android native version is out of scope for this PR.
</blockquote></details>

Version update was a rebase artifact. Fixed by rebasing over develop.

**Review by jkasten2 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/488#-:-N0bgnD6BXWub5EFBHkK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @adamschlesinger)

**Pull request merged**
