### PR TITLE
IS THERE AN OPTION TO GRAB MAINTAINER ATTENTION TO CHECK MY PR?

### PR DESCRIPTION
**Pull request by stopiccot**
Really guys... Can you please check it and say if it's ok or if it's not what is wrong with it.
https://github.com/OneSignal/OneSignal-Unity-SDK/pull/554

- - -
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/572)

### CODE REVIEW

**Comment by shepherd-l** [comment]
Sorry for the delay, we haven't had the chance to look at your PR yet. We will try to get to it as soon as we can.

**Comment by brismithers** [comment]
@stopiccot regarding this PR, can you please update the description to describe your changes.  Thanks!

**Comment by stopiccot** [comment]
@shepherd-l Had you had time to look through #554 PR?

**Comment by brismithers** [comment]
@stopiccot understand the frustration but please keep discussion under this PR, related to this PR.  Can you please update the description of this PR so we can understand the purpose of this change. Thank you.

**Pull request closed without merging**
