### PR TITLE
[FEATURE] InAppMessageAction docs and idiomatic fields

### PR DESCRIPTION
**Pull request by adamschlesinger**
### Changed
- Added inline documentation and Unity idiomatic fields to the `InAppMessageAction`

---
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/479)

### CODE REVIEW

**Review by jkasten2 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/479)* status: all files reviewed, 1 unresolved discussion (waiting on @adamschlesinger)

___
*[com.onesignal.unity.core/Runtime/Models/InAppMessageAction.cs, line 57 at r1](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/479#-N-dFJmv6u6iQ9xauClC:-N-dFJmv6u6iQ9xauClD:bgxuwfa) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/ad46584e5132cbb3036a0e8bf2601798a09cccce/com.onesignal.unity.core/Runtime/Models/InAppMessageAction.cs#L57)):*
> ```Smalltalk
> 
>     #region Native Field Handling
>         public string click_name;
> ```

Can we make this not public now? It would be confusing to app developers if they see `clickName` and `click_name`

**Review by adamschlesinger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/479)* status: all files reviewed, 1 unresolved discussion (waiting on @jkasten2)

___
*[com.onesignal.unity.core/Runtime/Models/InAppMessageAction.cs, line 57 at r1](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/479#-N-dFJmv6u6iQ9xauClC:-N-dHFTJ7zLMyqFJ4kNO:bmv90ke) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/ad46584e5132cbb3036a0e8bf2601798a09cccce/com.onesignal.unity.core/Runtime/Models/InAppMessageAction.cs#L57)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Can we make this not public now? It would be confusing to app developers if they see `clickName` and `click_name`
</blockquote></details>

We could but there are already uses of 3.0.0 in the wild and that would be a breaking change. I could mark it as deprecated.

**Review by jkasten2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/479)* status: all files reviewed, 1 unresolved discussion (waiting on @adamschlesinger)

___
*[com.onesignal.unity.core/Runtime/Models/InAppMessageAction.cs, line 57 at r1](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/479#-N-dFJmv6u6iQ9xauClC:-N-dJ1oX81Ee9R9f70yu:b-b6v321) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/ad46584e5132cbb3036a0e8bf2601798a09cccce/com.onesignal.unity.core/Runtime/Models/InAppMessageAction.cs#L57)):*
<details><summary><i>Previously, adamschlesinger (Adam Schlesinger) wrote…</i></summary><blockquote>

We could but there are already uses of 3.0.0 in the wild and that would be a breaking change. I could mark it as deprecated.
</blockquote></details>

ah good point, yes lets mark them as deprecated, pointing them to the new properties.

**Review by adamschlesinger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/479)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @jkasten2)

___
*[com.onesignal.unity.core/Runtime/Models/InAppMessageAction.cs, line 57 at r1](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/479#-N-dFJmv6u6iQ9xauClC:-N-dMZHO1MyqJ9RNjRsE:b-896fix) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/ad46584e5132cbb3036a0e8bf2601798a09cccce/com.onesignal.unity.core/Runtime/Models/InAppMessageAction.cs#L57)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

ah good point, yes lets mark them as deprecated, pointing them to the new properties.
</blockquote></details>

Done.

**Review by jkasten2 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/479#-:-N-dMiOL2G5XkAWBz5UK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @adamschlesinger)

**Pull request merged**
