### PR TITLE
Make OneSignalId and ExternalId nullable for Android

### PR DESCRIPTION
**Pull request by jinliu9508**
# Description
## One Line Summary
Make OneSignalId and ExternalId nullable for Android. The result of calling the getter will be null if no ID is currently available.

### Motivation
To keep all wrappers consistent when dealing with the IDs.

# Testing
## Manual testing
I have modified the example scene so that it displays "null" if calling the ID getter results in a null string. Tested on Android emulator pixel 3a API 34

# Affected code checklist
   - [ ] Notifications
      - [ ] Display
      - [ ] Open
      - [ ] Push Processing
      - [ ] Confirm Deliveries
   - [ ] Outcomes
   - [ ] Sessions
   - [ ] In-App Messaging
   - [ ] REST API requests
   - [ ] Public API changes

# Checklist
## Overview
   - [x] I have filled out all **REQUIRED** sections above
   - [x] PR does one thing
     - If it is hard to explain how any codes changes are related to each other then it most likely needs to be more than one PR
   - [x] Any Public API changes are explained in the PR details and conform to existing APIs

## Testing
   - [x] I have included test coverage for these changes, or explained why they are not needed
   - [x] All automated tests pass, or I explained why that is not possible
   - [x] I have personally tested this on my device, or explained why that is not possible

## Final pass
   - [x] Code is as readable as possible.
      - Simplify with less code, followed by splitting up code into well named functions and variables, followed by adding comments to the code.
   - [x] I have reviewed this PR myself, ensuring it meets each checklist item
      - WIP (Work In Progress) is ok, but explain what is still in progress and what you would like feedback on. Start the PR title with "WIP" to indicate this.

- - -
This change is [Reviewable](https://reviewable.io/reviews/OneSignal/OneSignal-Unity-SDK/699)

### CODE REVIEW

**Review by jkasten2 — APPROVED** [review]

**Review by shepherd-l — COMMENTED** [review]
Lgtm!

I think the editor platform methods could also return null because the subscription doesn't get created on the backend. What do you think? Do you have an preferences?
https://github.com/OneSignal/OneSignal-Unity-SDK/blob/user-model/main/com.onesignal.unity.core/Editor/Platform/UserManager.cs#L35

**Comment by nan-li** [comment]
Is this also addressed for the UserState object? `{"onesignalId": "123456789, "externalId": null}`

**Comment by jinliu9508** [comment]
> Lgtm!
> 
> I think the editor platform methods could also return null because the subscription doesn't get created on the backend. What do you think? Do you have an preferences? https://github.com/OneSignal/OneSignal-Unity-SDK/blob/user-model/main/com.onesignal.unity.core/Editor/Platform/UserManager.cs#L35

Ok I just made that change. I think it will keep the code consistent regarding the default value of the IDs.

**Comment by jinliu9508** [comment]
> Is this also addressed for the UserState object? {"onesignalId": "123456789, "externalId": null}

Yes, both null and "" will make the getter to return null.

**Comment by nan-li** [comment]
> > Is this also addressed for the UserState object? {"onesignalId": "123456789, "externalId": null}
> 
> Yes, both null and "" will make the getter to return null.

For the UserState that is passed to observers? I am not sure how everything is translated across Unity bridges, but [here ](https://github.com/OneSignal/OneSignal-Unity-SDK/blob/192d4f7ddad8b7f74519be05687888ae2924b1ab/com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalUnityBridgeUser.mm#L114)it uses the `jsonRepresentation` method which returns empty strings. Does it later translate to null in another layer?

**Comment by jinliu9508** [comment]
> > > Is this also addressed for the UserState object? {"onesignalId": "123456789, "externalId": null}
> > 
> > 
> > Yes, both null and "" will make the getter to return null.
> 
> For the UserState that is passed to observers? I am not sure how everything is translated across Unity bridges, but [here ](https://github.com/OneSignal/OneSignal-Unity-SDK/blob/192d4f7ddad8b7f74519be05687888ae2924b1ab/com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalUnityBridgeUser.mm#L114)it uses the `jsonRepresentation` method which returns empty strings. Does it later translate to null in another layer?

Unity string is nullable and yes this line of code `string.IsNullOrEmpty(id)? null : id;` later translate the string to null for either empty or null string from the native.

**Comment by nan-li** [comment]
> Unity string is nullable and yes this line of code `string.IsNullOrEmpty(id)? null : id;` later translate the string to null for either empty or null string from the native.

Ok! 👍🏼 Thanks! I did not know that also applied to the UserState

**Pull request merged**
