### PR TITLE
[FIX] Exported Android resources not functioning as intended

### PR DESCRIPTION
**Pull request by adamschlesinger**
### Changed
- Default export path for icons on Android changed to `Assets/Plugins/Android/OneSignalConfig/res`
### Removed
- Legacy AndroidManifest from past version of imported OneSignal Android SDK

---
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/430)

### CODE REVIEW

**Review by jkasten2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/430)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @adamschlesinger and @jkasten2)

___
*[com.onesignal.unity.android/Editor/SetupSteps/SetupManifestStep.cs, line 36 at r1](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/430#-MskfUReAJeSf8Hyg8Je:-MskfUReAJeSf8Hyg8Jf:bc9ch2e) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/0466541b3f1e3f0d567d8edac0aaa37e78a482a5/com.onesignal.unity.android/Editor/SetupSteps/SetupManifestStep.cs#L36)):*
> ```Smalltalk
>         var matches = Regex.Matches(contents, _manifestRegex);
>         foreach (var match in matches) {
>             if (match.ToString() != PlayerSettings.GetApplicationIdentifier(BuildTargetGroup.Android))
> ```

I believe we can remove this whole manifest step completely since we switched our Gradle release of the OneSignal-Andriod-SDK.

**Review by adamschlesinger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/430)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @jkasten2)

___
*[com.onesignal.unity.android/Editor/SetupSteps/SetupManifestStep.cs, line 36 at r1](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/430#-MskfUReAJeSf8Hyg8Je:-MtEoCGE6eYTJ1uvFa-X:b-l9dp0o) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/0466541b3f1e3f0d567d8edac0aaa37e78a482a5/com.onesignal.unity.android/Editor/SetupSteps/SetupManifestStep.cs#L36)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

I believe we can remove this whole manifest step completely since we switched our Gradle release of the OneSignal-Andriod-SDK.
</blockquote></details>

I think you're right. I'll need to test it without this step to confirm.

**Review by jkasten2 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/430#-:-Mtirwp_9Z-_eqyKSD21:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @adamschlesinger)

___
*[com.onesignal.unity.android/Editor/SetupSteps/SetupManifestStep.cs, line 36 at r1](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/430#-MskfUReAJeSf8Hyg8Je:-MtirU3ZEMJ2C_icOrcK:b-t2h50m) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/0466541b3f1e3f0d567d8edac0aaa37e78a482a5/com.onesignal.unity.android/Editor/SetupSteps/SetupManifestStep.cs#L36)):*
<details><summary><i>Previously, adamschlesinger (Adam Schlesinger) wrote…</i></summary><blockquote>

I think you're right. I'll need to test it without this step to confirm.
</blockquote></details>

We can merge this PR in for now so it doesn't hold up the release since you tested it. We can follow up with another PR to fully remove this if it work.

**Review by jkasten2 — APPROVED** [review]
Changes look good to me. Some commits could be squashed to clean up the git history though.

> Reviewed 72 of 72 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/430#-:-Mtui46VCZjO6X12Bama:bz1ksl4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @adamschlesinger)

**Pull request merged**
