### PR TITLE
Exclude Attribution folder on package creation

### PR DESCRIPTION
**Pull request by adamschlesinger**
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/413)

### CODE REVIEW

**Review by jkasten2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/413)* status: all files reviewed, 1 unresolved discussion (waiting on @adamschlesinger)

___
*[OneSignalExample/Assets/OneSignalPackager/Editor/OneSignalPackagePublisher.cs, line 14 at r1](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/413#-MptADwH2NbQqqozPXhi:-MptADwH2NbQqqozPXhj:b-sv8at8) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/62ccc47bfd026347e24534241af3a6f92d18ab08/OneSignalExample/Assets/OneSignalPackager/Editor/OneSignalPackagePublisher.cs#L14)):*
> ```Smalltalk
>     }
>     
>     [MenuItem("OneSignal/ExportUnityPackage")]
> ```

Is this menu item hidden or do we some how exclude this `OneSignalPackagePublisher` class from our release builds?

**Review by adamschlesinger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/413)* status: all files reviewed, 1 unresolved discussion (waiting on @jkasten2)

___
*[OneSignalExample/Assets/OneSignalPackager/Editor/OneSignalPackagePublisher.cs, line 14 at r1](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/413#-MptADwH2NbQqqozPXhi:-MptBIpD0ats7gDn2gHz:b-f3r14w) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/62ccc47bfd026347e24534241af3a6f92d18ab08/OneSignalExample/Assets/OneSignalPackager/Editor/OneSignalPackagePublisher.cs#L14)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Is this menu item hidden or do we some how exclude this `OneSignalPackagePublisher` class from our release builds?
</blockquote></details>

The OneSignalPackager directory is not included in any distributions.

**Review by jkasten2 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/413)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @adamschlesinger)

___
*[OneSignalExample/Assets/OneSignalPackager/Editor/OneSignalPackagePublisher.cs, line 14 at r1](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/413#-MptADwH2NbQqqozPXhi:-MptF1v05fhz5XOJuife:b-8fx2u7) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/62ccc47bfd026347e24534241af3a6f92d18ab08/OneSignalExample/Assets/OneSignalPackager/Editor/OneSignalPackagePublisher.cs#L14)):*
<details><summary><i>Previously, adamschlesinger (Adam Schlesinger) wrote…</i></summary><blockquote>

The OneSignalPackager directory is not included in any distributions.
</blockquote></details>

:+1:

**Review by jkasten2 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/413#-:-MptF5st2mwT1tN0phoU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @adamschlesinger)

**Pull request merged**
