### PR TITLE
Feature/package installer

### PR DESCRIPTION
**Pull request by adamschlesinger**
This takes functionality which previously had been delegated to a separate bootstrapper package and iterates on it. 

Now the installation of UPM based packages is offered when replacing the original OneSignal Unity SDK directly. Developers will no longer be required to find and install an alternate package in order to resolve the transition from legacy to new.

Additionally the single-use, non-interactive Bootstrapper class has been replaced by a more verbose "installer". This allows the end-user to be informed of the steps being taken on their project.

The individual package folder have been moved to the main directory so that the import installation step can be simulated. This also makes the code much easier to find for the devs.

This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/369)

### CODE REVIEW

**Review by jkasten2 — CHANGES_REQUESTED** [review]
> Reviewed 30 of 281 files at r3, 6 of 11 files at r4, 43 of 49 files at r5.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/369)* status: 75 of 281 files reviewed, 4 unresolved discussions (waiting on @adamschlesinger and @jkasten2)

___
*[bumpVersion.sh, line 2 at r4](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/369#-Mf3lXA9Dq2LzE3pepKc:-Mf3lXA9Dq2LzE3pepKd:bsupyip) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/f666a9bb2e62251efd86ed5d4e9866f9ecc45208/bumpVersion.sh#L2)):*
> ```Shell
> #!/bin/bash
> ```

Would be good to have a comment block explaining what this does. Looks like; bumps version numbers and makes a commit.
___
*[bumpVersion.sh, line 69 at r4](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/369#-Mf3l4f1DjgJUOo08dkI:-Mf3l4f1DjgJUOo08dkJ:b-jshxl9) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/f666a9bb2e62251efd86ed5d4e9866f9ecc45208/bumpVersion.sh#L69)):*
> ```Shell
>     done
> 
>     # update project version TODO
> ```

New TODO to address. Is it indented to follow up in this PR or in the future?
___
*[bumpVersion.sh, line 74 at r4](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/369#-Mf3lwW1827SYG-gwWAe:-Mf3lwW1827SYG-gwWAf:becwvsb) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/f666a9bb2e62251efd86ed5d4e9866f9ecc45208/bumpVersion.sh#L74)):*
> ```Shell
>     
>     # commit changes
>     git commit -m "Bumped version to ${new_version}"\
> ```

Version bump should be done on it's own branch. So a PR can be created and approved.
___
*[bumpVersion.sh, line 93 at r4](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/369#-Mf3mizp8bVed3bbTgjT:-Mf3mizp8bVed3bbTgjU:bvo4rtr) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/f666a9bb2e62251efd86ed5d4e9866f9ecc45208/bumpVersion.sh#L93)):*
> ```Shell
>      minor      Increment the MINOR version by 1 and reset PATCH to 0
>      patch      Increment the PATCH version by 1
>      build      Increment the project BUILD version by 1 (NYI)"
> ```

Do we want to add a build number? Drop BUILD number logic if we don't plan to implement.

**Review by adamschlesinger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/369)* status: 74 of 292 files reviewed, 4 unresolved discussions (waiting on @jkasten2)

___
*[bumpVersion.sh, line 2 at r4](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/369#-Mf3lXA9Dq2LzE3pepKc:-MfEAH_GEVZkg_gWtOwE:b-edj0mf) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/f666a9bb2e62251efd86ed5d4e9866f9ecc45208/bumpVersion.sh#L2)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Would be good to have a comment block explaining what this does. Looks like; bumps version numbers and makes a commit.
</blockquote></details>

Added in manual string at the top of the script which is also accessible from the terminal via -h -? or --help
___
*[bumpVersion.sh, line 69 at r4](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/369#-Mf3l4f1DjgJUOo08dkI:-MfEA-KG64ofcfvZJbvh:b-pg6k9n) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/f666a9bb2e62251efd86ed5d4e9866f9ecc45208/bumpVersion.sh#L69)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

New TODO to address. Is it indented to follow up in this PR or in the future?
</blockquote></details>

Added in the feature this was referencing in latest update.
___
*[bumpVersion.sh, line 74 at r4](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/369#-Mf3lwW1827SYG-gwWAe:-MfEAWPTEl-hEWrfs0nu:bvjv0ns) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/f666a9bb2e62251efd86ed5d4e9866f9ecc45208/bumpVersion.sh#L74)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Version bump should be done on it's own branch. So a PR can be created and approved.
</blockquote></details>

As discussed the entire purpose of the script has increased in scope and is now a full release composer. I have added the features of 
- Creating a release branch to which the version updates are committed to.
- Building a unity package file
- Creating a pull request from the release branch to main
- Creating a draft release in the github repo
___
*[bumpVersion.sh, line 93 at r4](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/369#-Mf3mizp8bVed3bbTgjT:-MfEB7OZBWcP0J1sAciC:b-j9dz2a) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/f666a9bb2e62251efd86ed5d4e9866f9ecc45208/bumpVersion.sh#L93)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Do we want to add a build number? Drop BUILD number logic if we don't plan to implement.
</blockquote></details>

Dropped. This is something to consider in the future but likely for app deployment only.

**Review by jkasten2 — CHANGES_REQUESTED** [review]
> Reviewed 198 of 281 files at r3, 5 of 11 files at r4, 6 of 49 files at r5, 13 of 13 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/369)* status: all files reviewed, 4 unresolved discussions (waiting on @adamschlesinger)

___
*[composeRelease.sh, line 221 at r7](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/369#-MfF1fYz-KMxtpsXryL6:-MfF1fYz-KMxtpsXryL7:bneu404) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/a0374f3c158c40e1b62a7519348926fb5c4690e9/composeRelease.sh#L221)):*
> ```Shell
>     --notes "TODO"
> 
> # return to workspace
> ```

:thumbsup: Nice handling with returning the existing branch and handling local changes with stash.
___
*[OneSignalExample/Assets/OneSignalPackager/Editor/OneSignalFileInventoryGenerator.cs, line 12 at r6](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/369#-MfEzu48BBw1GaXYrk5Q:-MfEzu48BBw1GaXYrk5R:b-oczbx) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/06cefb2f7ceb49bd7306cb9a4fae32f65970766c/OneSignalExample/Assets/OneSignalPackager/Editor/OneSignalFileInventoryGenerator.cs#L12)):*
> ```Smalltalk
> {
>     /// <summary>
>     /// Run from the internal OneSignal menu or cmdline to create a inventory resource to distribute
> ```

This comment notes that this is internal but how is this item hidden? Is there code somewhere else that hides the top level "OneSignal" menu?
___
*[OneSignalExample/Assets/OneSignalPackager/Editor/OneSignalSetupReset.cs, line 5 at r6](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/369#-MfF-oag7918PHVQnt1y:-MfF-oag7918PHVQnt1z:b6iqweh) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/06cefb2f7ceb49bd7306cb9a4fae32f65970766c/OneSignalExample/Assets/OneSignalPackager/Editor/OneSignalSetupReset.cs#L5)):*
> ```Smalltalk
> 
> /// <summary>
> /// For debugging all of the OneSignalSetupSteps
> ```

Same how is this being hidden question as above.
___
*[OneSignalExample/Assets/Scripts/OneSignalExampleBehaviour.cs, line 15 at r5](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/369#-Mf4KKze8aMZfMKfaUmO:-Mf4KJSc-jncxM1SMRAl:blr1k2r) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/b0690b4ce8f8293ce8ae292cded646fcb9b3f0fd/OneSignalExample/Assets/Scripts/OneSignalExampleBehaviour.cs#L15)):*
> ```Smalltalk
>                 .HandleInAppMessageClicked(HandleIamClicked)
>                 .Settings(new Dictionary<string, bool>() {
>                     { OneSignal.kOSSettingsAutoPrompt, false },
> ```

Recommend we keep these settings and `OneSignal.PromptForPushNotificationsWithUserResponse`. This is recommend to point out it is best not to prompt for notifications on app start. (In the major release auto prompt has been removed completely)

**Review by adamschlesinger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/369)* status: 264 of 294 files reviewed, 4 unresolved discussions (waiting on @jkasten2)

___
*[composeRelease.sh, line 221 at r7](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/369#-MfF1fYz-KMxtpsXryL6:-MfFXYMwEq5C1VeFI2tu:b-896fix) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/a0374f3c158c40e1b62a7519348926fb5c4690e9/composeRelease.sh#L221)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

:thumbsup: Nice handling with returning the existing branch and handling local changes with stash.
</blockquote></details>

Done.
___
*[OneSignalExample/Assets/OneSignalPackager/Editor/OneSignalFileInventoryGenerator.cs, line 12 at r6](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/369#-MfEzu48BBw1GaXYrk5Q:-MfFXtpJ3hz19VQP9ReX:bvp8xi9) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/06cefb2f7ceb49bd7306cb9a4fae32f65970766c/OneSignalExample/Assets/OneSignalPackager/Editor/OneSignalFileInventoryGenerator.cs#L12)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

This comment notes that this is internal but how is this item hidden? Is there code somewhere else that hides the top level "OneSignal" menu?
</blockquote></details>

Ah I can see why that's confusing. There are 2 directories in the `Assets` folder. `OneSignal` and `OneSignalPackager` (might rename for clarity). Only the code in the `OneSignal` folder is packaged for distribution and all of the "internal" menus are inside `OneSignalPackager`.
___
*[OneSignalExample/Assets/OneSignalPackager/Editor/OneSignalSetupReset.cs, line 5 at r6](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/369#-MfF-oag7918PHVQnt1y:-MfFYX6a5YXAhL2_ehtb:bchh49l) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/06cefb2f7ceb49bd7306cb9a4fae32f65970766c/OneSignalExample/Assets/OneSignalPackager/Editor/OneSignalSetupReset.cs#L5)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Same how is this being hidden question as above.
</blockquote></details>

See previous answer.
___
*[OneSignalExample/Assets/Scripts/OneSignalExampleBehaviour.cs, line 15 at r5](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/369#-Mf4KKze8aMZfMKfaUmO:-MfFXcBuB33jpFOjRMbE:bf7xu7r) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/b0690b4ce8f8293ce8ae292cded646fcb9b3f0fd/OneSignalExample/Assets/Scripts/OneSignalExampleBehaviour.cs#L15)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Recommend we keep these settings and `OneSignal.PromptForPushNotificationsWithUserResponse`. This is recommend to point out it is best not to prompt for notifications on app start. (In the major release auto prompt has been removed completely)
</blockquote></details>

This was pulled directly from the existing example behavior script. I'm not sure what you are asking here?

**Comment by jkasten2** [comment]
___
*[OneSignalExample/Assets/Scripts/OneSignalExampleBehaviour.cs, line 15 at r5](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/369#-Mf4KKze8aMZfMKfaUmO:-MfKgnKmCho8MiRnzpgK:b8ky29l) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/b0690b4ce8f8293ce8ae292cded646fcb9b3f0fd/OneSignalExample/Assets/Scripts/OneSignalExampleBehaviour.cs#L15)):*
<details><summary><i>Previously, adamschlesinger (Adam Schlesinger) wrote…</i></summary><blockquote>

This was pulled directly from the existing example behavior script. I'm not sure what you are asking here?
</blockquote></details>

Never mind, something might have went wrong with this other branch where it changed then was fixed in this branch. I looked the state of this file in the last release we shipped (2.13.6) and this branch matches it.
https://github.com/OneSignal/OneSignal-Unity-SDK/blob/3dc6b9ee4234783ca56bc2358026cd8708801d7d/OneSignalExample/Assets/OneSignal/Example/GameControllerExample.cs

**Comment by jkasten2** [comment]
___
*[OneSignalExample/Assets/OneSignalPackager/Editor/OneSignalFileInventoryGenerator.cs, line 12 at r6](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/369#-MfEzu48BBw1GaXYrk5Q:-MfKhmihA5JV624_EFbz:bzieg5g) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/06cefb2f7ceb49bd7306cb9a4fae32f65970766c/OneSignalExample/Assets/OneSignalPackager/Editor/OneSignalFileInventoryGenerator.cs#L12)):*
<details><summary><i>Previously, adamschlesinger (Adam Schlesinger) wrote…</i></summary><blockquote>

Ah I can see why that's confusing. There are 2 directories in the `Assets` folder. `OneSignal` and `OneSignalPackager` (might rename for clarity). Only the code in the `OneSignal` folder is packaged for distribution and all of the "internal" menus are inside `OneSignalPackager`.
</blockquote></details>

ah gotcha

**Review by jkasten2 — APPROVED** [review]
> Reviewed 3 of 343 files at r3, 19 of 305 files at r8, 197 of 337 files at r11, 51 of 97 files at r12, 12 of 15 files at r13, 30 of 33 files at r14, 5 of 7 files at r15.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/369)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @adamschlesinger)

**Review by jkasten2 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/369#-:-MfKjGZ9E9Kd8910tP59:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @adamschlesinger)

**Pull request merged**
