### PR TITLE
[FEATURE] Automate updating the CHANGELOG for releases

### PR DESCRIPTION
**Pull request by adamschlesinger**
Automates updating the CHANGELOG for releases

---
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/462)

### CODE REVIEW

**Review by jkasten2 — CHANGES_REQUESTED** [review]
Would like if this code was a bit more understandable from a quick look, suggest moving to it's own function.

Also would be helpful to show the before and after transformation this is doing to the changelog file.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/462#-:-MxuQfAR2uQppWnSdhG-:bg3peri)* status: all files reviewed, 1 unresolved discussion (waiting on @adamschlesinger)

___
*[composeRelease.sh, line 180 at r1](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/462#-MxuQVxQ8kGkbnYKM9lf:-MxuQVxQ8kGkbnYKM9lg:blx1qu9) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/bce26c45ecefbf937c733bcc77e27d9033f9db8d/composeRelease.sh#L180)):*
> ```Shell
> done
> 
> # update CHANGELOG
> ```

Could we move this new version code to it's own function with a lite description of what it does?

**Review by jkasten2 — COMMENTED** [review]
I also notice we get a merge conflicts all the time with the `CHANGELOG.md` since PRs touch the same line to add their own entry.

Would do you think about solving this in this PR or a follow up PR if now is not a good time?
Some ideas that come top of mind are 
* Have an "unreleased" directory, each PR adds it's own file.
* Format PRs in a specific way and this script and find and parse them.
* Maybe @iamwillshepherd has some ideas to on this topic?

> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/462#-:-MxuRVdY3jKkt5s2di2e:bplx178)* status: all files reviewed, 1 unresolved discussion (waiting on @adamschlesinger)

**Review by adamschlesinger — COMMENTED** [review]
I'd rather solve this in a separate PR. Those changes are a bit extensive.

> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/462#-:-MxuVJav05aYmE31Yme0:bizjr84)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jkasten2)

___
*[composeRelease.sh, line 180 at r1](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/462#-MxuQVxQ8kGkbnYKM9lf:-N--b-f4-BX6V-nXf4HR:bsj9ssa) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/bce26c45ecefbf937c733bcc77e27d9033f9db8d/composeRelease.sh#L180)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Could we move this new version code to it's own function with a lite description of what it does?
</blockquote></details>

Ditto here. I'm fine moving chunks of the script into methods but this should be done as a separate refactor PR.



_Code quote:_
```Shell
angelog_path="OneSignalExample/Assets/OneSignal/CHANGELOG
```

**Review by jkasten2 — APPROVED** [review]
Ok, we can omit my function suggestion to unblock the release, and we can tackle a larger refactor of this file in another PR.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/462#-:-N-4WO4uAcF7__y7KcyH:b-wjfev)* status: all files reviewed, 1 unresolved discussion (waiting on @jkasten2)

**Pull request merged**
