### PR TITLE
Fixed InstallEdm4uStep to properly work with UPM EDM4U installations

### PR DESCRIPTION
**Pull request by stopiccot**
# Description
### Motivation
EDM4U is a google unity package that is distributed in two versions: classic .unitypackage or .tgz via installing using Package Manager (https://developers.google.com/unity/archive). In our projects for the sake of keeping Assets folder as clean as possible we use second option. Right now InstallEdm4uStep fails to detect EDM4U version if it's installed via Package Manager / UPM and shows false warning on OneSignal SDK Setup window.

# Testing
## Unit testing
There are currently no unit tests for editor scripts like InstallEdm4uStep. Moreover it's pretty simple reflection code.

## Manual testing
There should be no warning sign next to Install EDM4U step in OneSignal SDK Setup window when EDM4U is installed using UPM

# Affected code checklist
   - [ ] Notifications
      - [ ] Display
      - [ ] Open
      - [ ] Push Processing
      - [ ] Confirm Deliveries
   - [ ] Outcomes
   - [ ] Sessions
   - [ ] In-App Messaging
   - [ ] REST API requests
   - [ ] Public API changes

# Checklist
## Overview
   - [x] I have filled out all **REQUIRED** sections above
   - [x] PR does one thing
     - If it is hard to explain how any codes changes are related to each other then it most likely needs to be more than one PR
   - [x] Any Public API changes are explained in the PR details and conform to existing APIs

## Testing
   - [x] I have included test coverage for these changes, or explained why they are not needed
   - [x] All automated tests pass, or I explained why that is not possible
   - [x] I have personally tested this on my device, or explained why that is not possible

## Final pass
   - [x] Code is as readable as possible.
      - Simplify with less code, followed by splitting up code into well named functions and variables, followed by adding comments to the code.
   - [x] I have reviewed this PR myself, ensuring it meets each checklist item
      - WIP (Work In Progress) is ok, but explain what is still in progress and what you would like feedback on. Start the PR title with "WIP" to indicate this.

- - -
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/554)

### CODE REVIEW

**Comment by stopiccot** [comment]
@shepherd-l @jkasten2

**Comment by stopiccot** [comment]
@shepherd-l @jkasten2 could you please take a look at this PR

**Comment by stopiccot** [comment]
@shepherd-l Had you had time to look through #554 PR?

**Comment by brismithers** [comment]
@stopiccot apologies we have not had a chance to validate your change just yet.  I appreciate your patience, given your reported description as this fixing a "false warning" its priority has been relatively lower.  We hope to evaluate this over the next couple of weeks.  Thanks!

**Comment by shepherd-l** [comment]
Thanks for doing this, the changes functionally look good. I did notice that I get a couple warnings on compile with [L50](https://github.com/OneSignal/OneSignal-Unity-SDK/pull/554/files#diff-dda4aa4d43ae3f01a8a5163d1f2b527cc192b2e30babdaa9871cf670bc6e2381R50) and [L83](https://github.com/OneSignal/OneSignal-Unity-SDK/pull/554/files#diff-dda4aa4d43ae3f01a8a5163d1f2b527cc192b2e30babdaa9871cf670bc6e2381R83) being protected and it being a sealed class. Would you mind updating these to be private to fix the warnings?

**Comment by stopiccot** [comment]
@shepherd-l Thanks for checking. I've fixed warnings

**Review by shepherd-l — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/554)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stopiccot)

**Pull request merged**
